name: Greetings

on: [workflow_dispatch]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: peterjgrainger/action-create-branch@v2.0.1
      with:
        # The branch to create
        branch: test-uat
    env:
      # This is necessary in order to push a commit to the repo
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged:  
