name: Greetings

on: [workflow_dispatch]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: peterjgrainger/action-create-branch@v2.0.1
      with:
        # The branch to create
        branch: test-uat
    - name: Execute script
      run: |
        echo $GITHUB_WORKSPACE
    - uses: actions/checkout@v2.3.4
      with:
        repository: ionut-matei/AzureFunctionsPlayground
        ref: test-uat
        path: deployments
    - name: Execute script
      run: |
        ls -l
    env:
      # This is necessary in order to push a commit to the repo
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged:  
      
